on:
  release:
    types: [created]

jobs:
  release-binaries:
    name: release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64, arm]
        goarm: [""] # Only relevant for arm architecture
        exclude:
          - goos: darwin
            goarch: arm
        include:
          - goos: linux
            goarch: arm
            goarm: "6"
          - goos: linux
            goarch: arm
            goarm: "7"
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1.49
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goarm: ${{ matrix.goarm }}
        goversion: 1.26.3
        binary_name: can2mqtt
        compress_assets: false
        project_path: src
        ldflags: -X "main.version=${{ github.ref_name }}"
      env:
        CGO_ENABLED: 0
